version: '3'

services:
  mongo:
    image: mongo
    environment:
      DB_NAME: nest
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
